# Generated by Django 4.2.1 on 2023-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_alter_post_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='post fotoğrafı'),
        ),
    ]
