# Generated by Django 4.2.1 on 2023-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postText',
            field=models.TextField(blank=True, null=True, verbose_name='post icerik'),
        ),
    ]
