# Generated by Django 4.2.1 on 2023-08-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_post_posti_mg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postİmg',
            new_name='postImg',
        ),
    ]
