# Generated by Django 4.2.1 on 2023-08-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(verbose_name='Yorum')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.post', verbose_name='Post')),
            ],
        ),
    ]
